### ISSUE TITLE
[FEAT] response format custom

### ISSUE THREAD

**Issue by hwiwonK** [unanchoi/KeyGo-server#1]
### Issue
- Response 형식 아래와 같이 custom
  ```json
  // 성공
    {
	    "success" : "true",
	    "message" : "message",
	    "detail" : "detail"
    }
  ```

  ```json
  // 실패
    {
	    "success" : "false",
	    "message" : "message",
    }
  ```

  ```json
  // 입력값 검증 오류
    {
	    "success" : "true",
	    "message" : "message",
            "detail" : 형식 오류 내용
    }
  ```

### Todo
- [x] success, fail response 형식 만들기
- [x] response code enum 생성
- [ ] 입력값 검증 fail response 형식 만들기
